# Generated by Django 4.1.2 on 2022-11-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Precio'),
        ),
    ]
